language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs
install:
  - echo "nothing needs to be installed"

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging

  # - docker-compose -f docker-compose-build.yaml build --parallel

  - docker build --no-cache ./udagram-reverseproxy -t $DOCKER_USERNAME/reverseproxy:$DOCKER_IMAGE_LATEST_VERSION
  - docker build --no-cache ./udagram-frontend     -t $DOCKER_USERNAME/udagram-frontend:$DOCKER_IMAGE_LATEST_VERSION
  - docker build --no-cache ./udagram-api-feed     -t $DOCKER_USERNAME/udagram-api-feed:$DOCKER_IMAGE_LATEST_VERSION
  - docker build --no-cache ./udagram-api-user     -t $DOCKER_USERNAME/udagram-api-user:$DOCKER_IMAGE_LATEST_VERSION
  - docker images

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push $DOCKER_USERNAME/udagram-api-feed:$DOCKER_IMAGE_LATEST_VERSION
  - docker push $DOCKER_USERNAME/udagram-api-user:$DOCKER_IMAGE_LATEST_VERSION
  - docker push $DOCKER_USERNAME/udagram-frontend:$DOCKER_IMAGE_LATEST_VERSION
  - docker push $DOCKER_USERNAME/reverseproxy:$DOCKER_IMAGE_LATEST_VERSION
